// <auto-generated />
using System;
using System.Collections.Generic;
using Manager_Service.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Manager_Service.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Manager_Service.Models.ApplicationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Applicant")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Manager")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QueueProgramId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QueueProgramId");

                    b.ToTable("Applications");
                });


            modelBuilder.Entity("Manager_Service.Models.ApplicationModel", b =>
                {
                    b.HasOne("Manager_Service.Models.QueueProgramsModel", "QueueProgram")
                        .WithMany()
                        .HasForeignKey("QueueProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueProgram");
                });
#pragma warning restore 612, 618
        }
    }
}
